### ISSUE TITLE
Squiggly heredoc having broken indentation applied to content of doc

### ISSUE THREAD

**Issue by lparry** [ruby-formatter/rufo#136]
Hi,

We are looking at using this on an large existing codebase and our spec suite caught what seems to be a bug in rufo. I've got a tiny example of a failing spec [here](https://github.com/lparry/rufo/commit/c263dee260e3aac498f20a74b43dbb828b1f2cd7).

input:
```ruby
<<~EOF
           #{1}
           #{2}
    EOF
```

expected output:
```ruby
<<~EOF
  #{1}
  #{2}
EOF
```

actual output:
```ruby
<<~EOF
  #{1}
           #{2}
EOF
```

I've been poking around in rufo's source but I'm not having much luck following what's going on. Maybe someone smarter than me can figure it out?

**Comment by gingermusketeer** [comment]
This should be fixed in `0.4.2`. Thanks to @JWoodbr!
