### ISSUE TITLE
Exiting with a non-zero exit code breaks Neoformat

### ISSUE THREAD

**Issue by jgrau** [ruby-formatter/rufo#18]
Tools like neoformat treats non-zero exit codes as errors and will discard the returned text from rufo. I'm not sure what the best practice is but I would expect a tool (like rufo) to return zero if there was no errors (ie, the tool ran successfully).

**Comment by danielma** [comment]
Thanks for opening an issue @jgrau 

rufo has a special exit code for when code was changed. [This was introduced to improve editor integration](https://github.com/ruby-formatter/rufo/commit/068bf0b417f4b8a82c5b14f7d5858f5cdf42a713). The idea is that an editor can safely ignore rufo (not make any changes to the open buffer) if `rufo` exits with `0`, and the editor plugin only needs to apply changes for an exit code of `3`

You can read about the exit codes [in the README](https://github.com/ruby-formatter/rufo/tree/0e3fd5ab02c0f159a3c6141729afc6038f65fc92#exit-codes). If `neoformat` is broken with current versions of rufo, I'd recommend opening a pull request to that project

**Comment by jgrau** [comment]
Thanks for the quick reply. I've opened an issue on `neoformat` :)

**Comment by splattael** [comment]
Refs sbdchd/neoformat#110

**Comment by mjago** [comment]
@jgrau as of commit #43 you are now able to pass Rufo the -x flag to be returned 0 on success, non-zero on error.

**Comment by mjago** [comment]
Closing as fixed with #43
