### ISSUE TITLE
How to work in vscode with Remote Development.

### ISSUE THREAD

**Issue by JMDC-SUN** [ruby-formatter/rufo#182]
Info
Platform: Win
Vetur version: 0.21.0
VS Code version: Version: 1.36.0-insider (user setup)
with Remote Development
Problem
I use it in Vscode + Remote Development extension, but not work.

> 「rufo not available in path. Ensure rufo gem is installed」

but, I installed rufo.
```
bash-4.2# rufo -v
rufo 0.7.0
```

How to work in vscode with Remote Development.

**Comment by gingermusketeer** [comment]
Hi this is the repo for the rufo gem not the vscode extension. Hopefully you have found a solution to this otherwise try raising an issue on https://github.com/bessey/vscode-rufo
