### ISSUE TITLE
`REGEX` pattern causes formatting error: `the given text is not a valid ruby program (it has syntax errors)`

### ISSUE THREAD

**Issue by gencer** [ruby-formatter/rufo#184]
open a ruby file. Write some piece of code. And put this code to somewhere at the beginning:

```
REGEX_PATTERN = /\A(?=.*\p{L})*\z/.freeze
```

Now try to format `.rb` file. It will fail.

```
Error: the given text is not a valid ruby program (it has syntax errors)
```

**Comment by gingermusketeer** [comment]
I think this has been fixed recently as I am not able to reproduce. Please reopen this if it is still an issue.
