### ISSUE TITLE
Preservation of spacing is not working

### ISSUE THREAD

**Issue by cdimartino** [ruby-formatter/rufo#187]
I'd love to use `rufo` but it keeps stepping on my coworkers tireless work aligning arguments. Any ideas as to why it removes spacing here:

```ruby
    include A
    extend  B

    validates :some_long_attr, presence: true
    validates :shorter_one,    presence: true
    validates :other,          presence: true
```

formats to:

```ruby
    include A
    extend B

    validates :some_long_attr, presence: true
    validates :shorter_one, presence: true
    validates :other, presence: true
```

**Comment by gingermusketeer** [comment]
This was something that rufo supported in the past but was removed. Supporting this is complicated and it does not minimise version control diffs, one of Rufo's goals. 

For example if we add a new attribute which is longer (or remove the longest attribute) then we end up with a diff like the following:

```diff
< validates :some_long_attr, presence: true
< validates :shorter_one,    presence: true
< validates :other,          presence: true
---
> validates :a_new_and_even_longer_attr, presence: true
> validates :some_long_attr,             presence: true
> validates :shorter_one,                presence: true
> validates :other,                      presence: true
```

However using the approach that rufo takes we end up with:
```diff
> validates :a_new_and_even_longer_attr, presence: true
```

Hopefully this makes sense.
