### ISSUE TITLE
How to handle ruby files detected by content

### ISSUE THREAD

**Issue by mmlb** [ruby-formatter/rufo#190]
Is there a way for `rufo .` to detect files that aren't obviously ruby related (Gemfile, *.rb) by the file name alone? Some files in one of the projects I work with have no extension and aren't standard ecosystem file names and so rufo skipped it.

**Comment by mmlb** [comment]
I kind of wanted rufo to do file type detection by reading file magic, but that would go against the "no deps" mantra, so #201 is good enough compromise, thanks!

**Comment by gingermusketeer** [comment]
@mmlb I agree that we would need to have either have to have a dependency for that or build something that would still be slow or unreliable. Good to hear that #201 is a good compromise!
