### ISSUE TITLE
Quoted keys break parsing

### ISSUE THREAD

**Issue by TranquilMarmot** [ruby-formatter/rufo#192]
Trying to run `rufo` against:

```rb
broken = {
    :'Some-Key' => 'Breaks Parsing'
}
```

Causes it to break with:

```
Rufo::Bug: unexpected node: string_content at [[2, 6], :on_tstring_content, "Some-Key", #<Ripper::Lexer::State: EXPR_FNAME>] at [[2, 6], :on_tstring_content, "Some-Key", #<Ripper::Lexer::State: EXPR_FNAME>]
```

**Comment by gingermusketeer** [comment]
@TranquilMarmot This is working for me on the latest version. I suspect that it was related to one of the other bugs that was fixed.

Please reopen this if it is still a problem.
