### ISSUE TITLE
Rufo 0.8.0 breaks when running on input files/directories not within the current directory

### ISSUE THREAD

**Issue by taylorthurlow** [ruby-formatter/rufo#206]
Consider the following directories and file: `/code/project/app/foo.rb`

If my current directory is `/code/project/app`, then running `rufo foo.rb` or `rufo .` works as expected.

However, if my current directory is `/code/project`, and I run `rufo app`, then it fails when trying to format `app/foo.rb` because it's trying to load the file with the path `foo.rb` rather than `app/foo.rb`.

**Comment by gingermusketeer** [comment]
@taylorthurlow This should be fixed in 0.8.1. Thanks for creating the issue.

**Comment by taylorthurlow** [comment]
@gingermusketeer No problem, thanks for working on Rufo! I consider it invaluable to my day-to-day work.
