### ISSUE TITLE
Node modules folder is being formatted

### ISSUE THREAD

**Issue by gingermusketeer** [ruby-formatter/rufo#209]
I am seeing the following file getting formatted `./node_modules/node-sass/src/libsass/extconf.rb`

Perhaps it should be included in the ignore list?

**Comment by gingermusketeer** [comment]
Or should we try and reuse .gitignore files which typically include this?

**Comment by pmk1c** [comment]
Using `.gitignore` as default exclusion list sounds very reasonable to me! :+1:
