### ISSUE TITLE
<%== %> syntax not supported

### ISSUE THREAD

**Issue by gingermusketeer** [ruby-formatter/rufo#210]
Rails supports `<%== "test" %>` which translates to `<%= raw("test") %>`.

**Comment by taylorthurlow** [comment]
This might be a similar issue, but the parser chokes on

```erb
<%= pager_wrap do -%>
  <li class="next"><%= link_to t('links.new'), new_role_path %></li>
<% end %>
```

Notice the `-%>`. Removing the `-` solves the problem.

**Comment by gingermusketeer** [comment]
Ah yes. Can tackle both of these together.
