### ISSUE TITLE
Add configuration option to preserve the existing style of quotes

### ISSUE THREAD

**Issue by i-tsvetkov** [ruby-formatter/rufo#234]
Hi, I think that having a way to format a messy ruby codebase is great, but I think that the changes to the quote style in large codebases are stopping a lot of people from adopting the gem.

The changes to the quote style can create very large diffs that can't be reviewed effectively in a timely manner.

I also think that the quote style as a formatting option is far from what most people are searching when they need automatic code formatting to improve the code readability of existing code, for example, fixing indentation, missing/excessive brackets and long lines are more important for readability than the quote style.

**Comment by BatuhanW** [comment]
@i-tsvetkov You can create a `.rufo` file at the root of the project and add this line;

```
quote_style :single
```

**Comment by i-tsvetkov** [comment]
I understand that rufo will keep double quotes with sting interpolation in them but if there is a string using double quotes and there is no string interpolation in it rufo with the suggested configuration will change the quote style from double to single quotes.

The point I'm trying to make here is that sometimes it is better to ignore the quotes that are not conforming to some preferred style and apply the other formatting options that are going to add value to the readability of legacy (or just messy) code.

I think that this will open the door for incremental adoption to people that are not comfortable with large diffs but would like to improve the readability of their code.

@BatuhanW

**Comment by gingermusketeer** [comment]
@i-tsvetkov Rufo previously had a lot of configuration options that allowed for this sort of thing , not for quotes but for other configuration options. However we are moving away from this in favour of less configuration.

Consistent code is not just great for readability but also searching and making wide ranging changes. All of this is easier with consistent code.

I understand that your suggestion would make it easier to start using a tool like Rufo however the other consideration here is the development and maintenance. At the moment there are not too many people involved in Rufo and better Heredoc support or moving to a setup more similar to how [prettier](http://prettier.io) works is higher priority so I am going to close this for now.
