### ISSUE TITLE
Add a none option to quote_style and/or provide a setting to disable it

### ISSUE THREAD

**Issue by lockland** [ruby-formatter/rufo#258]
When you are working on a legacy code replacing quotes is really danger, so have a setting to disable this format rule would be amazing.

That mechanism was already developed as we can see on code below:

https://github.com/ruby-formatter/rufo/blob/b87e21e504d34d39d80d7186ff777c279f02d843/lib/rufo/formatter.rb#L644-L654

But it is not possible just return on that method because of the code below

https://github.com/ruby-formatter/rufo/blob/b87e21e504d34d39d80d7186ff777c279f02d843/lib/rufo/formatter.rb#L639-L641

Looking on that pieces of code I've started to wonder if run rufo on its own code would not break the everything.

**Comment by kzkn** [comment]
> When you are working on a legacy code replacing quotes is really danger, so have a setting to disable this format rule would be amazing.

Can you give me an example of what specific codes are danger?

**Comment by kzkn** [comment]
Merged. Thanks!
