### ISSUE TITLE
Comma added at the end of a multiline hash in fonction call

### ISSUE THREAD

**Issue by martinos** [ruby-formatter/rufo#26]
I noticed that if a pass a hash to a function and I put every key-value pair on its own line, the last key-value pair gets a comma appended to it.

```ruby
    create(
      name: "Joe",
      email: "bob@example.net",
      customer_id: cust.id,
    )
```
In this case a comma is added after the `customer_id` value. 

I think this is not the expected behaviour.

**Comment by splattael** [comment]
Hi @martinos,

thanks for reporting. Can you share your rufo settings (in `~/.rufo`)?

A comma only gets appended if `trailing_commas` is set to `:always`.

Kind regards,
  Peter

**Comment by martinos** [comment]
Sure, I should have already done that.

Here it is:
```
indent_size                 2
spaces_inside_hash_brace    :always
spaces_inside_array_bracket :never
spaces_around_equal         :one
spaces_in_ternary           :one
spaces_in_suffix            :one
spaces_in_commands          :dynamic
spaces_around_block_brace   :one
spaces_after_comma          :dynamic
spaces_around_hash_arrow    :one
spaces_around_when          :one
spaces_around_dot           :no
spaces_after_lambda_arrow   :no
spaces_around_unary         :no
spaces_around_binary        :one
parens_in_def               :yes
double_newline_inside_type  :no
visibility_indent           :align
trailing_commas             :always
align_comments              true
align_assignments           false
align_hash_keys             false
align_case_when             true
align_chained_calls         true
```
My rufo version:

```
$ rufo -v
rufo 0.1.0
```

**Comment by martinos** [comment]
It's the first time that I look at the [spec](https://github.com/ruby-formatter/rufo/blob/master/spec/lib/rufo/formatter_source_specs/trailing_commas.rb.spec), I got my answer there.

**Comment by splattael** [comment]
@martinos :+1:

There is already a [discussion](https://github.com/ruby-formatter/rufo/issues/2#issuecomment-315627976) to have only "One True Format". https://github.com/ruby-formatter/rufo/issues/2#issuecomment-315627976

Feel free to join the fun :sunglasses:
