### ISSUE TITLE
With "Format Selection", always wrongly removes all indentation

### ISSUE THREAD

**Issue by suan** [ruby-formatter/rufo#260]
Given

```ruby
  def foo
    some_call
  end
```

If I highlight the moddle line and run "Format Selection" command, it results in

```ruby
  def foo
some_call
  end
```

(all indentation removed). Would love a fix (or pointer on how to fix)

**Comment by tnir** [comment]
@suan I am not sure what interface you used, but if you use Rubo on VS Code, you can ask this at https://github.com/jnbt/vscode-rufo/issues. If not, let me know what interface (e.g. IDE) you are using 😄

**Comment by suan** [comment]
Ah, sorry got confused. I've filed it over there and will close this. Thanks!
