### ISSUE TITLE
syntax error, unexpected end-of-input on erb

### ISSUE THREAD

**Issue by joshunger** [ruby-formatter/rufo#266]
```
rufo --version
rufo 0.13.0

rufo _head.erb   
_head.erb:11 syntax error, unexpected end-of-input
```

![image](https://user-images.githubusercontent.com/2301847/128603064-9bb4eee5-3878-4d73-bbec-1ab92b0cddca.png)

**Comment by effleurager** [comment]
Might be the errant space in there, is this still an issue if you replace it with `LocationService::LANGUAGE_REGION_CODES_WITH_ENGLISH`?

**Comment by joshunger** [comment]
@effleurager the issue still exists if I remove the space

**Comment by effleurager** [comment]
> @effleurager the issue still exists if I remove the space

Can you send the full block for that if-statement?

**Comment by joshunger** [comment]
@effleurager does this work?

```
<% if @alternates
  Service::SOMETHING.each do |code| %>
    <link rel="alternate" hreflang="<%= code[0..1] %>" href="">
  <% end
  @alternates[:with].each do |language, replacement| %>
    <link rel="alternate" hreflang="<%= language %>" href="">
  <% end %>
<% else %>
  <link rel="alternate" hreflang="en" href="">
<% end %>
```

**Comment by effleurager** [comment]
That give a syntax error on line 2.
The following does work:
```erb
<% if @alternates %>
  <% Service::SOMETHING.each do |code| %>
    <link rel="alternate" hreflang="<%= code[0..1] %>" href="">
  <% end %>
  <% @alternates[:with].each do |language, replacement| %>
    <link rel="alternate" hreflang="<%= language %>" href="">
  <% end %>
<% else %>
  <link rel="alternate" hreflang="en" href="">
<% end %>
```

**Comment by joshunger** [comment]
@effleurager thanks for the workaround but isn't the code I pasted valid too?

**Comment by effleurager** [comment]
Just checked, it actually is a workaround. The problem lies in Ripper requiring the block and if statements to be completed with `end`. That requires taking adding `\nend` twice as a code wrapper in https://github.com/ruby-formatter/rufo/blob/b3f3aedf759d792761ad52e6bddb9ed51ffc6731/lib/rufo/erb_formatter.rb#L107. While entirely possible to hack a fix together, it'd be better to figure out the required number of `\nend` to be added for a given code string

**Comment by joshunger** [comment]
@effleurager @gingermusketeer thank you.
