### ISSUE TITLE
Expected op **, not ... at [[17, 16], :on_op, "...", ENDARG] (Rufo::Bug)

### ISSUE THREAD

**Issue by homko** [ruby-formatter/rufo#278]
bundler: failed to load command: rufo (/usr/local/bin/rufo)
/usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3582:in `bug': Expected op **, not ... at [[17, 16], :on_op, "...", ENDARG] (Rufo::Bug)
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3164:in `consume_op'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2182:in `visit_params'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:416:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2062:in `block in visit_def_from_name'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3387:in `indent'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2061:in `visit_def_from_name'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2005:in `block in visit_def'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3707:in `push_hash'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2004:in `visit_def'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:410:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3467:in `block in indent_body'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3391:in `indent'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3466:in `indent_body'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1578:in `visit_bodystmt'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:380:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1973:in `block in visit_class'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3714:in `push_type'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1957:in `visit_class'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:398:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3467:in `block in indent_body'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3391:in `indent'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3466:in `indent_body'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1578:in `visit_bodystmt'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:380:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1990:in `block in visit_module'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3714:in `push_type'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1983:in `visit_module'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:400:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:201:in `visit'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:177:in `format'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:146:in `format'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:107:in `format_file'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:85:in `block in format_args'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:78:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:78:in `format_args'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:40:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:12:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/exe/rufo:4:in `<top (required)>'
	from /usr/local/bin/rufo:25:in `load'
	from /usr/local/bin/rufo:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'

**Comment by kzkn** [comment]
maybe fixed by #281

**Comment by kzkn** [comment]
#281 has merged. Give it try.
If it still occurs, please share the reproducing Ruby code.
