### ISSUE TITLE
Introduce CHANGELOG.md?

### ISSUE THREAD

**Issue by splattael** [ruby-formatter/rufo#3]
Hi,

I've just released [v0.1.0](https://rubygems.org/gems/rufo/versions/0.1.0) which basically reflects rufo's new home in gemspec. :sparkles: 
This release is also the first release in the "post-@asterite era".

Speaking of the new era. I'd like to add a changelog which keeps track of notable changes in rufo.

Personally, I've used [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) format in some projects.
I like it but it can be any other format. I don't care as long as it is consistent :nerd_face: 

What are your thoughts on this topic?

Kind regards,
  Peter

**Comment by luislavena** [comment]
Hello,

I've used Keep a Changelog approach in several projects, including internals ones, with great results. In Ruby land is quite common the `History.md` file which is a predecessor of `CHANGELOG.md` idea (not to compare with the GNU one).

Now the project has been solidified with release 0.1.0, looking forward for future changes.

Cheers!

**Comment by bessey** [comment]
I went for the Keep a Changelog approach, PR #27
