### ISSUE TITLE
issue trying to gem install rufo

### ISSUE THREAD

**Issue by DemICE** [ruby-formatter/rufo#307]
apparently my OS blocks access to a file needed for the installation?

![image](https://user-images.githubusercontent.com/15263230/236179634-e7200a4c-3920-4071-8317-dd2019128d97.png)

i've checked the folder's and the file's permissions and i have full control (my pc has only 1 account and its the administrator account)
![image](https://user-images.githubusercontent.com/15263230/236180166-2db3d672-7e6d-49c2-94a9-c42e07006778.png)

**Comment by kzkn** [comment]
Perhaps this is not an issue for rufo. Hence, I won't be able to help much.

Wouldn't it behave the same way when installing other gems?

**Comment by DemICE** [comment]
well that's a bummer.
i havent tried to install any other gems yet so i don't know.

**Comment by kzkn** [comment]
I see, so if you examine it from there, you may be able to find the cause of the error.
If you find that rufo is the cause, please open the issue again.
