### ISSUE TITLE
Why does rufo replace the \n string escape with actual newline? Can we not?

### ISSUE THREAD

**Issue by Nitrodist** [ruby-formatter/rufo#308]
I have code that is like this:

```
def abc
  print "Hello\nWorld"
end
```

After formatting with Rufo, it changes the code to this:

```
  print "Hello
World"
```
Often I have additional code in a string I'm interpolating - for example `"#{a}\n#{b}\n#{c}\n"`. I can understand this usecase, sure. But, simple calls like`.join("\n")` result in a needless newline.

It's much more readable if I was able to write `.join("\n")` IMO!

**Comment by Nitrodist** [comment]
Actually, this appears to be a rufo-vim issue 😢  https://github.com/ruby-formatter/rufo-vim/issues/28

**Comment by kzkn** [comment]
Does it reproduce using rufo standalone, or only with rufo-vim?
When run standalone, it worked correctly on my environment.

```
$ rufo --version
rufo 0.16.1
$ rufo <<EOF
def abc
  print "Hello\nWorld"
end
EOF
def abc
  print "Hello\nWorld"
end
```

**Comment by kzkn** [comment]
This is not a rufo's issue but rufo-vim's one ( And it has already opened as https://github.com/ruby-formatter/rufo-vim/issues/28 ). So close this issue.
