### ISSUE TITLE
"Invalid yield" error in ERB files on ruby 3.3.0

### ISSUE THREAD

**Issue by mloughran** [ruby-formatter/rufo#319]
Formatting any ERB file containing `<%= yield %>` (as is customary in a template) returns an error on ruby `3.3.0`:

	% ruby -v
	ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
	% rufo -v
	rufo 0.17.0
	% cat test.erb
	<%= yield %>
	% rufo test.erb
	test.erb:1 Invalid yield
	% echo $?
	1

but worked fine on ruby `3.2.2`:

	% ruby -v
	ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
	% rufo -v
	rufo 0.17.0
	% cat test.erb
	<%= yield %>
	% rufo test.erb
	% echo $?
	0

**Comment by kzkn** [comment]
Thanks for the report :smile: 
This is caused by a breaking change on Ripper. Ripper produces `nil` for just `yield` on Ruby 3.3.0.

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ ruby -rripper -e "p Ripper.sexp('yield')"
[:program, [[:yield0]]]

$ ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
$ ruby -rripper -e "p Ripper.sexp('yield')"
nil
```

We may have to wait for Ruby itself to be fixed :thinking:

**Comment by mloughran** [comment]
Thanks for investigating and identifying the issue 👍.

Is it worth raising an issue on the ruby tracker (I can't [see anything related](https://bugs.ruby-lang.org/search?utf8=✓&q=ripper&all_words=&all_words=1&titles_only=&issues=1&open_issues=1&attachments=0&options=1&commit=Search))? I suspect you're better placed to do so than me 😄

**Comment by kzkn** [comment]
I've opened: https://bugs.ruby-lang.org/issues/20186
