### ISSUE TITLE
Alerting user to bad squiggly heredoc formatting on broken Ruby versions

### ISSUE THREAD

**Issue by mjago** [ruby-formatter/rufo#36]
@gingermusketeer pointed out that we should probably notify users where they are likely to be affected by incorrect squiggly heredoc formatting due to a Ripper bug:
> @mjago Given that this bug causes rufo to change the behaviour of the code and users may not pick it up if they do not check the changes carefully. Do you think we need to alert users to this bug if they are running a version of ruby with this issue?
Perhaps we should raise an exception, warn or skip the file if there is a squiggly heredoc present and they are running an unpatched version of ruby?

Affected Ruby versions are 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1

Should we detect squiggly heredoc usage on these versions and flag a warning to stderr? Or something else?

The above is only relevant once PR #33 is merged - currently Rufo crashes in these circumstances, but with PR #33 the squiggly heredoc is potentially formatted incorrectly (since Ripper loses information).

The fix is to upgrade to 2.3.5 or 2.4.2 where fixes to Ripper have been backported.

Related issue: #6

**Comment by gingermusketeer** [comment]
I think flagging the issue via a warning is a good approach. Also we should probably skip formatting the file.

**Comment by bessey** [comment]
Agreed, warning to STDERR and pass through file as is to STDOUT seems like the right thing to do.

Alternatively we could drop support for earlier versions, but given how rare / easily worked around a heredoc string with multiple embedded expressions is, I prefer your proposition.

**Comment by mjago** [comment]
It would be feasible to skip the squiggly heredoc rather than the whole file (which would require reopening the original source file) but this is maybe too much trouble for a _fixed_ issue.

What about ```Warning: file(s) foo.rb, bar.rb have not been formatted due to a problem with Ruby version 3.2.4 - please update to Ruby 3.2.5 to fix your formatting! See https://github.com/ruby-formatter/wiki/Ripper-Bug for more info```

Also do we need a -no-heredoc-warning switch option?

**Comment by mjago** [comment]
PR #37 aims to address this warning and avoid formatting files on Ruby versions where Ripper is broken.

**Comment by mjago** [comment]
Closed with #37
