### ISSUE TITLE
Cut 0.2.0

### ISSUE THREAD

**Issue by bessey** [ruby-formatter/rufo#40]
Everything in the 0.2.0 milestone is complete, any objections to cutting a new gem version? Did we want to resolve #32 first?

**Comment by mjago** [comment]
We must remember to update the README, which is woefully out-of-date.
Also, fixes have just been applied to Ruby 2.5.0 to remove the remaining parsing oddness w.r.t squiggly heredocs, so I should modify for 2.5.0 to reflect that (we currently have workarounds). I don't think these changes will be backported to 2.3 and 2.4.

**Comment by bessey** [comment]
The README PR is merged. Seems to me its OK to cut a release now. Not sure I have the credentials to do so though!

**Comment by mjago** [comment]
I would say so too 👍 . There is a bug that can break code in the current release for one thing (fixed now). And the config checker is in place to warn of config changes, which has already been useful to me!

**Comment by splattael** [comment]
Sooo, release? Like now? :grin: 

I'd take over!

BTW, https://rubygems.org/gems/rufo is missing some owners :smirk:
We should extend the list? WDYT?

**Comment by splattael** [comment]
After :twisted_rightwards_arrows: merging #55 I can release `0.2.0`.

**Comment by bessey** [comment]
I don't mind not having publish rights so long as someone cuts 0.2.0 now :P but I certainly wouldn't say _no_ to such rights either.

**Comment by gingermusketeer** [comment]
:shipit:

**Comment by splattael** [comment]
Version `0.2.0` released: https://rubygems.org/gems/rufo/versions/0.2.0 :tada:
