### ISSUE TITLE
Rufo spec viewer

### ISSUE THREAD

**Issue by mjago** [ruby-formatter/rufo#42]
I've taken a look at generating a html-rendered output of our specs.
The result output is [here](https://htmlpreview.github.io/?https://github.com/ruby-formatter/rufo/blob/spec_viewer/spec/viewer/output.html).
The script is in the spec_viewer branch [here](https://github.com/ruby-formatter/rufo/blob/spec_viewer/spec/viewer/generate.rb).

Each pair of actual / expected code segments are scanned with Rippers lexer.
The lexical tokens are then used to a) rebuild the code b) highlight and render the code.

Each token type is associated with a theme following the [base16 format](http://chriskempson.com/projects/base16/) (MIT licence) which means there are dozens of themes readily available etc.

Each code rebuild is tested to ensure the lexer output reflects our specs and provides a form of Ripper regression testing.

The html output / page structure is a bare bones proof of principle but it would be easy to offer a couple of themes (light / dark), and spec catagories etc.

Currently the generator is run via ruby spec/viewer/generate.rb (ruby version 2.3.5, 2.4.2, 2.5.0dev).

Thoughts?

**Comment by splattael** [comment]
Wow, nice! :+1: I :heart: it!

I wonder if it's possible to browse the specs by "category" (per spec file or something)?

Currently, staring at all 741 specs at once is a bit overwhelming :astonished: :smile:

**Comment by danielma** [comment]
Very cool! I think @splattael's suggestion about browsing by category would be great

**Comment by mjago** [comment]
I agree with categorisation. 

I'm also looking at how much test data is required to test each sample in each combination of settings (since we have much reduced settings now). Clearly most results are duplicates and can be simply tagged.

That would be a good regression test, and enable selecting any combination of settings within the viewer.

Maybe we should think of setting up a jekyll github site. I have used this [doc theme](http://idratherbewriting.com/documentation-theme-jekyll/) in the past?

**Comment by mjago** [comment]
Regarding the viewer I've been working on modifying the test system to run all specs on all combinations of settings. This works by maintaining a compressed diff of all differences of the various combinations differing from the default settings. Those diffs also enable the viewer to view the specs with any combination of configuration.

![screen shot 2017-10-26 at 21 56 29](https://user-images.githubusercontent.com/18483/32076940-96616e02-ba99-11e7-9f21-5ba3a4ccb98d.png)

**Comment by mjago** [comment]
I've taken a first stab at generating a static site displaying the examples, and potentially expanding to a Rufo web-site. It uses Jekyll and an MIT licensed theme (minimal-mistakes).
[You can see here](http://martynjago.co.uk/rufo-site/).

All examples are displayed with default settings, but also with any settings that affect that example as in [here](http://martynjago.co.uk/rufo-site/docs/trailing_commas/) and [here](http://martynjago.co.uk/rufo-site/docs/and_or_not/).

The complete website can be run by github's (gh-pages) mechanism (under a branch of gh-pages) from the Rufo github repo.

**Comment by mjago** [comment]
Here are a couple of possible bugs (?) detected using the alternate settings viewing aspect:
### align_case_when
```ruby
# BEFORE

case 1
when  2  then  3
else  4
end

```
```ruby
# BECOMES

case 1
when 2 then 3
else 4
end
```
```ruby
# with setting :align_case_when true

case 1
when 2 then 3
else        4
end
```

### spaces_around_binary
```ruby
# BEFORE

1+  2

```
```ruby
# BECOMES

1+  2

```
```ruby
# with setting :spaces_around_binary :one

1+2
```

**Comment by bessey** [comment]
This is brilliant! Definitely seems worth setting up a `rufo/rufo.github.io` and putting this in it.

**Comment by mjago** [comment]
@bessey Thanks. I've set up a gh-pages branch so it can be seen at [https://ruby-formatter.github.io/rufo/](https://ruby-formatter.github.io/rufo/)

**Comment by splattael** [comment]
@mjago Wow! This is so beautiful :heart_eyes: 

This URL should definitely  go in the README :rocket:

**Comment by mjago** [comment]
Closing as specs now render to html  https://ruby-formatter.github.io/rufo/
