### ISSUE TITLE
Deleted issues

### ISSUE THREAD

**Issue by martinos** [ruby-formatter/rufo#5]
Last week I have created an issue about Ruby 2.1. I am wondering why it was deleted and not just closed. I think that the issue would have helped people to know on which version is supported by the gem.

**Comment by danielma** [comment]
@martinos sorry about that. The original repo was deleted and so we had to transfer to a new organization. We have the code history, but we are missing github specific history (pull requests and issues). If you're willing to create the issue again, please do!

**Comment by martinos** [comment]
Thanks, this clears things up. Maybe I could just change the README.md file
to tell what Ruby version is supported.

**Comment by splattael** [comment]
@martinos Thanks for reporting! The README now lists all supported Ruby versions :)

**Comment by mjago** [comment]
@splattael only works down to ruby 2.2.4 (as in running ALL the specs) I believe

**Comment by splattael** [comment]
@mjago Oh, thanks for trying! :+1: I've updated the README.
