### ISSUE TITLE
Heredoc hash values have errant comma

### ISSUE THREAD

**Issue by gisikw** [ruby-formatter/rufo#61]
Hiya! Came across this issue when testing rufo's changes to a codebase. Rufo adds a trailing comma to hash args, which can break heredocs, as follows:

```ruby
{
  content: <<-EOF
    This is a heredoc
  EOF
}
```

...gets transformed to
```ruby
{
  content: <<-EOF
    This is a heredoc
  EOF,
]
```

Which will yield the error:
```shell
test.rb:5: can't find string "EOF" anywhere before EOF
test.rb:2: syntax error, unexpected end-of-input, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
```

In cases of heredocs, commas simply can't be placed without breaking the terminator.

**Comment by gingermusketeer** [comment]
Thanks for reporting this. I think the expected behavior, with trailing commas enabled, would be:
```
{
  content: <<-EOF,
    This is a heredoc
  EOF
}
```

I get a syntax error with: 

```
{
  content: <<-EOF
    This is a heredoc
  EOF
  , 
}
```

Does that sound correct to you?

**Comment by gisikw** [comment]
Yep, counterintuitive as it looks, that seems to work!
