### ISSUE TITLE
Multi-line word array literal

### ISSUE THREAD

**Issue by hopsoft** [ruby-formatter/rufo#77]
Lexer chokes on multi-line word array literal. 

Here's the code that triggers the error.

```ruby
header = %w(
  organization
  full_name
  phone_number
  email
  tags
  assignments
  created
)
```

Here's the error.

```
/usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3429:in `bug': Expected token on_ident, not on_words_sep at [[27, 19], :on_words_sep, "\n          ", #<Ripper::Lexer::
State: EXPR_BEG>] (Rufo::Bug)
```

**Comment by hopsoft** [comment]
I just realized that this is a duplicate of #73

**Comment by gingermusketeer** [comment]
@hopsoft Thanks triaging this :) Would you be able to submit a PR with a test? You can mark the tests as pending and then it can be fixed by someone. See #75 as an example.

**Comment by hopsoft** [comment]
It appears that #68 may have resolved this problem.

**Comment by mjago** [comment]
Fixed in HEAD
