### ISSUE TITLE
Wrong Indents for method after backslash?

### ISSUE THREAD

**Issue by fukayatsu** [ruby-formatter/rufo#8]
- Without `.rufo` file
- `rufo -v #=> rufo 0.1.0`

Given this code:

```ruby
class Foo
  def self.bar(_)
  end

  bar \
  def baz
  end
end
```

The formatter will change it to:

```ruby
class Foo
  def self.bar(_)
  end

  bar \
    def baz
  end
end
```

Is there any settings to avoid this behavior?

**Comment by splattael** [comment]
@fukayatsu Interesting pattern. I wonder what's the reason behind this kind of formatting?

Your code could be written as:

```ruby
bar def baz
end
```

Actually, I would prefer this type of formatting.

Any thoughts on this?

**Comment by fukayatsu** [comment]
> Your code could be written as:

I agree.  I just wanted to align `def` and `end`.
I may rewrite my code like:

```ruby
def baz
end

bar :baz
```

**Comment by splattael** [comment]
@fukayatsu :+1:
