### ISSUE TITLE
Syntax error when file contains foreign languages in strings

### ISSUE THREAD

**Issue by ernsheong** [ruby-formatter/rufo#82]
When a string in a Ruby file contains "é" or any other non-Latin a-zA-Z character (foreign languages), the file fails syntax checking. 

`Error: the given text is not a valid ruby program (it has syntax errors)`

**Comment by ernsheong** [comment]
Also, `ruby -c ./file-name.rb` runs successfully on the target file, but generates error on rufo.

**Comment by luislavena** [comment]
Can you provide more details on the version of Ruby and the platform used?

```
$ echo $LANG

$ ruby --version

$ ruby -e 'p Encoding.default_internal, Encoding.default_external, "".encoding'
```

Cheers.

**Comment by ernsheong** [comment]
Thanks for the response. Here is the first part:

```
$ echo $LANG
en_GB.UTF-8
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
$ ruby -e 'p Encoding.default_internal, Encoding.default_external, "".encoding'
nil
#<Encoding:UTF-8>
#<Encoding:UTF-8>
```

It is also failing in Gitlab CI, which is of a slightly different environment.

**Comment by luislavena** [comment]
Hello @ernsheong, I was unable to reproduce:

```ruby
# éxito as comment

def foo
  puts "éxito as string"
end

def éxito
  puts "method!"
end
```

```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

$ bundle show
Gems included by the bundle:
  * bundler (1.16.1)
  * rufo (0.2.0 ea4dc14)

$ bin/rufo 1.rb

$ echo $?
0
```

Does your file works correctly when executed via Ruby?

```
$ ruby -c 1.rb
Syntax OK
```

**Comment by ernsheong** [comment]
This is quite odd. From the command line on my Mac, everything passes just fine as above.

But in the VS Code plugin and in Gitlab CI, it complains:
![image](https://user-images.githubusercontent.com/1343284/37010212-753767fc-2125-11e8-88da-27f6e6d65cc9.png)

Error disappears when I comment out the line:
![image](https://user-images.githubusercontent.com/1343284/37010224-82238e78-2125-11e8-9d56-b172056491e4.png)

I am using the global install of rufo via `gem install rufo`

**Comment by luislavena** [comment]
@ernsheong I'm still unable to reproduce:

```ruby
# éxito as comment

def foo
  puts "éxito as string"
end

def éxito
  puts "method!"
end

HASH = {
  :BJ => "Benin",
  :BL => "Saint Barthélemy",
  :BM => "Bermuda",
}
```

```
$ ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

# gem version instead of repository one
$ bin/rufo --version
rufo 0.2.0

$ bin/rufo 1.rb

$ echo $?
0
```

Maybe VS Code is pointing/using a different version of Ruby than the one you have accessible via the terminal. Same could apply to GitLab CI, right now you haven't provided us the output received on GitLab CI, so we don't know.

Will be great if you can produce a small repository that reproduces the issue and point us to investigate. The more details, the better.

Cheers.

**Comment by ernsheong** [comment]
Thanks for the effort. I will reopen once I figure out a way to reproduce this reliably...

**Comment by constantm** [comment]
I just ran into this as well - had a constant declared on a Ruby class that used an inverted apostrophe. Not sure if this will help at all, but here are the details:

```ruby
class DidAThingBadge < Badge
  DESCRIPTION = "You’ve done the bare minimum!"
end
```

```
➜  echo $LANG
en_GB.UTF-8
➜  ruby -e 'p Encoding.default_internal, Encoding.default_external, "".encoding'
nil
#<Encoding:UTF-8>
#<Encoding:UTF-8>
➜  rufo -v
rufo 0.4.0
➜  ruby -v
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin17]
```

**Comment by 1st8** [comment]
I can confirm, that this is something related to the vscode plugin.

**Comment by bessey** [comment]
I am the maintainer of the vscode plugin. I don't really use the plugin
myself at the moment but I am happy to take a pull request, its not a very
complicated plugin
<https://github.com/bessey/vscode-rufo/blob/master/src/rufo.ts>!

Matt

**Comment by eiseneker** [comment]
I'm experiencing this issue from the CLI:

```
bundle exec rufo app/
Error: your_file.rb has syntax errors
```

This will fail on characters such as: 
```
ä ’ 上
```

Environment:
```
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
```

Environment is a Docker container `FROM ruby:2.5.0`. Same command works okay on my host machine running ruby 2.5.0 (macOS)
