### ISSUE TITLE
Alignment of method arguments?

### ISSUE THREAD

**Issue by ivoanjo** [ruby-formatter/rufo#83]
Hello there! First of all: thank you very much for Rufo! I hope it takes off like a Falcon rocket :rocket: 

I was playing with it on one for my personal projects, and noticed that unlike the examples listed in the [aligning call parameters](https://github.com/ruby-formatter/rufo#unobtrusive-by-default) section of the README, the alignment on method **arguments** is not preserved.

### Example:

Input file:

```ruby
def method_with_a_lot_of_args(
  hello:,
  world:,
  foo:,
  bar:,
  baz:
)
  puts "hello, world!"
end

method_with_a_lot_of_args(
  hello: 1,
  world: 2,
  foo: 3,
  bar: 4,
  baz: 5
)
```

Rufo output:

```ruby
def method_with_a_lot_of_args(
                              hello:,
                              world:,
                              foo:,
                              bar:,
                              baz:)
  puts "hello, world!"
end

method_with_a_lot_of_args(
  hello: 1,
  world: 2,
  foo: 3,
  bar: 4,
  baz: 5,
)
```

My expectation: I would like for Rufo to also keep the existing alignment, as it does on method calls.

What do you think? I know that Rufo is not about personal opinion, but this result was quite unexpected to me, as I wouldn't expect different rules for calling a method from declaring a method.

Thanks! 🙏

**Comment by gingermusketeer** [comment]
Thanks for reporting this. Do you happen to know how this is commonly handled in the community?

I personally would do what you have done and suspect that would be the more common approach, but be good to get some data.

**Comment by gingermusketeer** [comment]
@ivoanjo Wow that is amazing, thanks for the solid research.

I think I agree with your suggestion. The rationale being:
1. As you have shown not many codebase would be drastically affected.
2. The [new formatter](https://github.com/ruby-formatter/rufo/tree/new-formatter) will hopefully apply the same logic for arrays, hashes, method calls and method definitions.
