### ISSUE TITLE
alignment agnosticism

### ISSUE THREAD

**Issue by jrochkind** [ruby-formatter/rufo#90]
This is a great project, thanks. I like that it tries to respect some alignment choices agnostically, [Unobtrusive by default](https://github.com/ruby-formatter/rufo#unobtrusive-by-default). 

Trying it out on my code, here is one choice where it doesn't:

```ruby
something = if whatever
  "foo"
else
  "bar"
end
```

This seems reasonable to me, but rufo insists on:

```ruby
something = if whatever
              "foo"
             else
               "bar"
             end
```

thoughts? Maybe I'm wrong that this is reasonable!

**Comment by gurgeous** [comment]
For what it's worth, I agree with @jrochkind on this one. I have a ton of code like this (assignment with if, case, or begin). Though really I'm just happy to have auto-formatting of any kind :)

**Comment by martinos** [comment]
What I do in case for the time being:

```
something =
  if whatever
    "foo"
  else
    "bar"
  end
```
This is reasonable for me.

**Comment by thefliik** [comment]
I agree with the OP. Just opened up this duplicate issue before realizing that this issue already addresses it. You can see some specific examples where the current formatting is a real problem (at least from my perspective) here: #119 

Personally, I can't use rufo with the current enforcement.

**Comment by rmosolgo** [comment]
I love rufo's approach, but won't continue with it because of this reason. In fact, I don't really care about indentation, but I found that it was indenting to places other than tab stops, so to add code, I couldn't simply `tab` over, instead, I had to occasionally add spaces to get _between_ the tabs. What I mean is: 

```ruby
things = if xyz 
           abcd
         else 
           efgh
         end 
```

Since the number of spaces before `abcd` and `else` is odd, my editor's `tab` key doesn't align with them properly.

**Comment by gingermusketeer** [comment]
Been looking into this issue and would like to get some feedback on what we should do here. I can see two options that seem like good approaches.

# Option 1

The first is what @martinos suggests above:
```ruby
a = 
  if true
    1
  else
    2
  end

a_really_long_name = 
  if true
    1
  else
    2
  end
```

**Pros**
- Small and focused diffs for version control tools when changing a single line. See below.
```diff
< a =
---
> a_new_name =
```

# Option 2
Keep the first line of the expression on the same line as the assignment.

```ruby
a = if true
    1
  else
    2
  end

a_really_long_name = if true
    1
  else
    2
  end


```

**Pros**
- Diff remains a single line:
```diff
< a = if true
---
> a_new_name = if true
```
**Cons**
- Diff is not as small.

# Option 3
```ruby
a = if true
  1
else
  2
end

a_really_long_name = if true
  1
else
  2
end


```

**Pros**
- Text editors have the correct indentation when pressing enter after the `end` keyword.

**Cons**
- Indentation does not indicate clearly where the assignment statement ends.

**Comment by gingermusketeer** [comment]
Decided to go with Option 2
