### ISSUE TITLE
Tilde heredocs with trailing comma has indent problem

### ISSUE THREAD

**Issue by bonty** [ruby-formatter/rufo#93]
I found indent problem while using tilde heredocs inside of hash.

Example:

```ruby
{
  content: <<~EOF,
    heredoc
  EOF
}
```

Result:

```ruby
{
  content: <<~EOF,
  heredoc
EOF
}
```

**Comment by lparry** [comment]
I'm pretty sure I've stumped on some overlapping bugs, I've added my own test cases here: https://github.com/lparry/rufo/commit/0df5d33cbc3d51ac1a1e53fd0269c4d7d26c13e4

The trailing comma with comment is particularly bad as it's breaking the public key in the heredoc
